export const materialOptions = [
  { value: "onu_nueva", label: "ONU NUEVA", type: "serial" },
  { value: "onu_retorno", label: "ONU RETORNO", type: "serial" },
  { value: "router_nuevo", label: "ROUTER NUEVO", type: "serial" },
  { value: "router_retorno", label: "ROUTER RETORNO", type: "serial" },
  { value: "drop_servicio_inicial", label: "DROP DE SERVICIO LECTURA INICIAL", type: "meters" },
  { value: "drop_servicio_final", label: "DROP DE SERVICIO LECTURA FINAL", type: "meters" },
  { value: "drop_cliente_inicial", label: "DROP DEL CLIENTE LECTURA INICIAL", type: "meters" },
  { value: "drop_cliente_final", label: "DROP DEL CLIENTE LECTURA FINAL", type: "meters" },
  { value: "utp", label: "UTP", type: "meters" },
  { value: "patch_cord", label: "PATCH CORD", type: "cantidad" },
  { value: "conectores_azules", label: "CONECTORES AZULES", type: "cantidad" },
  { value: "conectores_verdes", label: "CONECTORES VERDES", type: "cantidad" },
  { value: "conectores_azules_daniados", label: "CONECTORES AZULES DAÑADOS", type: "cantidad" },
  { value: "conectores_verdes_daniados", label: "CONECTORES VERDES DAÑADOS", type: "cantidad" },
  { value: "acoples_azules", label: "ACOPLES AZULES", type: "cantidad" },
  { value: "acoples_verdes", label: "ACOPLES VERDES", type: "cantidad" },
  { value: "acoples_azules_daniados", label: "ACOPLES AZULES DAÑADOS", type: "cantidad" },
  { value: "acoples_verdes_daniados", label: "ACOPLES VERDES DAÑADOS", type: "cantidad" },
  { value: "splitter_1x8", label: "SPLITTER 1X8", type: "cantidad" },
  { value: "splitter_1x16", label: "SPLITTER 1X16", type: "cantidad" },
  { value: "rosetas", label: "ROSETAS", type: "cantidad" },
  { value: "pigtail", label: "PIGTAIL", type: "cantidad" },
  { value: "nap", label: "NAP", type: "cantidad" },
  { value: "tensores", label: "TENSORES", type: "cantidad" },
  { value: "etiquetas", label: "ETIQUETAS", type: "cantidad" },
  { value: "cajas_empalme", label: "CAJAS DE EMPALME", type: "cantidad" },
  { value: "precintos", label: "PRECINTOS", type: "cantidad" },
  { value: "flejes", label: "FLEJES", type: "cantidad" },
  { value: "hebillas", label: "HEBILLAS", type: "cantidad" },
];